version: '3'
services:
  be:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "1323:1323"
    networks: 
      - gofolio-network
  fe:
    build:
      context: ./web
      dockerfile: dockerfile
    ports:
      - "5173:5173"
    networks: 
      - gofolio-network
  mariadb:
    image: mariadb:latest
    container_name: mariadb-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
    ports:
      - "3306:3306"
    # volumes:
    #   - ./data:/var/lib/mysql
    restart: always
    networks: 
      - gofolio-network

networks:
  gofolio-network:
    external: true